--CREATE TYPE--
CREATE TYPE "Role" AS ENUM ('CUSTOMER', 'TENANT', 'AGENT');
CREATE TYPE "NotificatioType" AS ENUM ('INFO', 'WARNING', 'ALERT', 'MESSAGE');
CREATE TYPE "NotificationStatus" AS ENUM ('READ', 'UNREAD');
CREATE TYPE "TicketStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'CLOSED');

--CREATE TABLE--
CREATE TABLE "User"(
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role "Role" NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "User_id_role_key" UNIQUE (id, role)
);

CREATE TABLE "Tenant"(
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  "userId" UUID NOT NULL UNIQUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
);

CREATE TABLE "Customer"(
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  "userId" UUID NOT NULL UNIQUE,
  "tenantId" UUID NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE,
  FOREIGN KEY ("tenantId") REFERENCES "Tenant"(id) ON DELETE CASCADE
);


CREATE TABLE "Agent"(
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  "userId" UUID NOT NULL UNIQUE,
  "tenantId" UUID NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE,
  FOREIGN KEY ("tenantId") REFERENCES "Tenant"(id) ON DELETE CASCADE
);

CREATE TABLE "Notification"(
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL,
  type "NotificatioType" NOT NULL,
  status "NotificationStatus" NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
);

CREATE TABLE "Ticket"(
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status "TicketStatus" NOT NULL DEFAULT 'OPEN',
  "customerId" UUID NOT NULL,
  "tenantId" UUID NOT NULL,
  "agentId" UUID,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("customerId") REFERENCES "Customer"(id) ON DELETE CASCADE,
  FOREIGN KEY ("tenantId") REFERENCES "Tenant"(id) ON DELETE CASCADE,
  FOREIGN KEY ("agentId") REFERENCES "Agent"(id) ON DELETE SET NULL
);